config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'profiles/index'
  resources :comments
  resources :likes , only: [:create, :destroy]
  devise_scope :user do
    get "/users", to: "devise/registrations#new"
    get "/users/password", to: "devise/passwords#new"
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }


  resources :users, only: [:show]


  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"


  get 'home/about'
  get 'posts/myposts'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5, maximun: 100}
    validates :description, presence:true, length: {minimum: 5, maximun: 500}
    validates :keywords, presence:true, length: {minimum: 5, maximun: 100}

    has_many_attached :images
    belongs_to :user
    has_many :comments
    has_many :likes
    before_create :randomize_id
         private
         def randomize_id
            begin
              self.id = SecureRandom.random_number(1_000_000_000)
            end while Post.where(id: self.id).exists?
         end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def myposts
    @posts = Post.all
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :keywords, :user_id, images:[])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm-8 col-10 mt-4" style="margin:auto; background-color: #f8f8f8; border-radius: 6px; padding: 15px;">
<h1>New post</h1>
<%= form_with(model: post) do |form| %>
  <div>
  <%invalid = post.errors.include?(:title)%>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control"%>

    <%if invalid%>
      <p style="color:red; font-size: 12px;">
        <%= post.errors.full_messages_for(:title).join(" , ")%>
      </p>
    <%end%>
  </div>
  <div>
    <%= form.text_field :user_id, type: "hidden", value: current_user.id%>
  </div>
  <div>
    <%invalid = post.errors.include?(:description)%>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
    <%if invalid%>
      <p style="color:red; font-size: 12px;">
        <%= post.errors.full_messages_for(:description).join(" , ")%>
      </p>
    <%end%>
  </div>

  <div>
    <%invalid = post.errors.include?(:keywords)%>
    <%= form.label :keywords, style: "display: block" %>
    <%= form.text_field :keywords, class:"form-control" %>
    <%if invalid%>
      <p style="color: red; font-size: 12px;">
        <%= post.errors.full_messages_for(:keywords).join(" , ")%>
      </p>
    <%end%>
  </div>

  <div>
    <%= form.label "Select images / videos"%>
    <%= form.file_field :images, multiple:true%>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary col-12 mt-3"%>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container">
  <p>
    <%= post.title %>
  </p>

  <p>
    <%= post.description %>
  </p>

  <p>
    <%= post.keywords %>
  </p>

  <p>
    <%#= post.user.email %>
  </p>

  <p>
    <%= link_to "", post, class:"post-link" %>
  </p>
  <%if user_signed_in?%>
    <%like = current_user.likes.find_by(post: post)%>
      <%if like.nil?%>
      <%= button_to "like", likes_path, params: {like: {post_id: post.id}}, method: :post,  class: "btn-like" %>
    <%else%>
      <%= button_to "Unlike", like_path(like), method: :delete , class: "btn-unlike"%>
    <%end%>
  <%end%>
  <p><%= post.likes.count%> Likes</p>
 
  <% post.images.each do |image| %>
    <%= image_tag(image, style: "object-fit:cover; width: 200px; height: 600px") %>
  <%end%>
</div>
 <p>
    <%= link_to post.user.email, post.user%>
  </p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post") %>
<%if user_signed_in?%>
  <%if current_user.admin?%>
    You are an Admin
  <%end%>
  <%current_user.follow_requests.each do |request|%>
    <%= request.followerable.email %> Wants to follow you
    <%= button_to "Accept", accept_path(@user)%>
    <%= button_to "Decline", decline_path(@user)%>
  <%end%>
  Followers
    <% current_user.followers.each do |follower| %>
      <p><b> <%= link_to follower.email, follower%></b></p>
    <%end%>
    <br />
    Following
     <% current_user.following.each do |following| %>
      <p><b> <%= link_to following.email, following%></b></p>
    <%end%>
<%end%>

<p style="color: green"><%= notice %></p>

<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

app/views/posts/myposts.html.erb
<%= stylesheet_link_tag("post") %>
<p style="color: green"><%= notice %></p>

<div id="posts" class="text-center">
  <% @posts.each do |post| %>
    <%if post.user == current_user%>
        <%= render post %>
    <%end%>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <%= render "form", post: @post %>
</div>
<br>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>
<%= link_to "Back to posts", posts_path %>

<%if user_signed_in?%>
  <%if current_user == @post.user%>
    <div>
      <%= link_to "Edit this post", edit_post_path(@post) %> |
      <%= button_to "Destroy this post", @post, method: :delete %>
    </div>
  <%end%>
<%end%>

<%= render "comments/form", comment: @comment%>
<% @post.comments.each do |comment|%>
  <%= comment.text%>
  <br>
<%end%>