config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'profiles/index'
  resources :comments
  resources :likes , only: [:create, :destroy]
  devise_scope :user do
    get "/users", to: "devise/registrations#new"
    get "/users/password", to: "devise/passwords#new"
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users, controllers: {
        registrations: 'users/registrations'
  }


  resources :users, only: [:show]


  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"


  get 'home/about'
  get 'posts/myposts'
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer class="bg-body-tertiary text-center text-lg-start">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 Copyright:
    <a class="text-body" href="https://github.com/AleHS01">AleHS</a>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar.css" %>
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand"%>
    <%= form_with url: profiles_index_path, method: :get do |form|%>
      <%= form.search_field :query, value: params[:query], placeholder: "Search", class: "search-field" %>
      <%= form.submit "Search" , class: "btn btn-primary"%>
    <%end%>
    <%if user_signed_in? && current_user.avatar.attached?%>
            <%= image_tag current_user.avatar, style: "width: 50px; height: 50px;" %>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Upload Post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "About", home_about_path, class: "nav-link"%>
        </li>
        <%if user_signed_in?%>
          <%if current_user.admin?%>
            <%=link_to "Admin Panel", rails_admin_path, class: "nav-link"%>
          <%end%>
          <li class="nav-item">
            <%= link_to "View My Profile", current_user, class:"nav-link"%>
          </li>
          <li>
            <%= link_to "View My Posts", posts_myposts_path, class:"nav-link"%>
          </li>
          
          <li>
            <%= link_to "Edit Account", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link"%>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
    <%= render "layouts/footer"%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>